/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(example-code)'}/nav/login` | `/nav/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(example-code)'}/nav/reset-password` | `/nav/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(example-code)'}/nav/signup` | `/nav/signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/codecheck`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/layout`; params?: Router.UnknownInputParams; } | { pathname: `/home/save`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/user/monetization`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(example-code)'}/nav/login` | `/nav/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(example-code)'}/nav/reset-password` | `/nav/reset-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(example-code)'}/nav/signup` | `/nav/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/codecheck`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/password`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/home/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/home/save`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/user`; params?: Router.UnknownOutputParams; } | { pathname: `/user/monetization`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(example-code)'}/nav/login${`?${string}` | `#${string}` | ''}` | `/nav/login${`?${string}` | `#${string}` | ''}` | `${'/(example-code)'}/nav/reset-password${`?${string}` | `#${string}` | ''}` | `/nav/reset-password${`?${string}` | `#${string}` | ''}` | `${'/(example-code)'}/nav/signup${`?${string}` | `#${string}` | ''}` | `/nav/signup${`?${string}` | `#${string}` | ''}` | `/auth/codecheck${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/password${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/home/layout${`?${string}` | `#${string}` | ''}` | `/home/save${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/user${`?${string}` | `#${string}` | ''}` | `/user/monetization${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(example-code)'}/nav/login` | `/nav/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(example-code)'}/nav/reset-password` | `/nav/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(example-code)'}/nav/signup` | `/nav/signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/codecheck`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/layout`; params?: Router.UnknownInputParams; } | { pathname: `/home/save`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/user/monetization`; params?: Router.UnknownInputParams; };
    }
  }
}
